# Generated by Django 4.0.5 on 2022-06-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_patient_covid_positive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='covid_positive',
            field=models.BooleanField(default=False),
        ),
    ]
