# Generated by Django 4.0.5 on 2022-07-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_hospital_is_covid_care_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='ambulance_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hospital',
            name='oxygen_concentrator_available',
            field=models.BooleanField(default=False),
        ),
    ]
