# Generated by Django 4.0.5 on 2022-07-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_hospital_ambulance_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='ambulance_available',
            field=models.BooleanField(default=False, verbose_name='Ambulance'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='bed_occupied',
            field=models.IntegerField(default=0, verbose_name='No. of Beds Occupied'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='beds_available',
            field=models.IntegerField(default=0, verbose_name='No. of Beds Available'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='is_covid_care_center',
            field=models.BooleanField(default=False, verbose_name='Covid Care Center'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='no_icu_beds',
            field=models.IntegerField(default=0, verbose_name='No. of ICU Beds'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='oxygen_concentrator_available',
            field=models.BooleanField(default=False, verbose_name='Oxygen concentrator'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='total_no_of_beds',
            field=models.IntegerField(default=0, verbose_name='Total No. of Beds'),
        ),
    ]
